name: prometheus
author: eightballer
version: 0.1.0
type: skill
description: The scaffold skill is a scaffold for your own skill implementation.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  __init__.py: bafybeib3kw4s2hqfeu3oh6s5kkmccwzlhjppd5xij3osi6fjhdnpfalh74
  behaviours.py: bafybeicojtihhl4n542sjnam6o3wkbmyp7dy2benwuzcald64nmnav7k6a
  dialogues.py: bafybeicqhvcoqwbmqkqxxtfv3qi3dlhkgaowvlevxrtveesksjo7cw4roe
  handlers.py: bafybeiaxuyfp6mrleyruqhucqiy5mbce5ruqs3n5n7jb2dxpe73js6mxia
  strategy.py: bafybeidmgt4k7hpqcoulo6acosamuhpelj6tsco3gy3dovt35r5f373jke
  tests/test_skill.py: bafybeih5jeglqi7qkk4v3unaiuteyutv5k6k7diytm4xelhbiwoprjcd44
fingerprint_ignore_patterns: []
connections:
- eightballer/prometheus:0.1.1:bafybeicy4ck2wvauo2vh6ji64xrzlgezh27powi6ztokr4yujtf3cft6wi
contracts: []
protocols:
- eightballer/prometheus:1.0.0:bafybeidxo32tu43ru3xlk3kd5b6xlwf6vaytxvvhtjbh7ag52kexos4ke4
- eightballer/http:0.1.0:bafybeid75xhq7hfdt7sgj7yrn44yj57xrgxscaw34ir46tndfzvodioxme
skills: []
behaviours:
  prometheus_behaviour:
    args: {}
    class_name: PrometheusBehaviour
handlers:
  http_handler:
    args: {}
    class_name: HttpHandler
  prometheus_handler:
    args: {}
    class_name: PrometheusHandler
models:
  data_request_model:
    args:
      body: ''
      decimals: 5
      method: GET
      outputs: []
      url: ''
    class_name: DataRequestModel
  http_dialogues:
    args: {}
    class_name: HttpDialogues
  prometheus_dialogues:
    args:
      enabled: true
      metrics:
      - name: num_retrievals
        type: Gauge
        description: Number of data retrievals
        labels: {}
      - name: num_requests
        type: Gauge
        description: Number of data requests served
        labels: {}
      - name: memory_usage
        type: Gauge
        description: Memory usage of the agent
        labels: {}
      - name: cpu_usage
        type: Gauge
        description: CPU usage of the agent
        labels: {}
    class_name: PrometheusDialogues
dependencies: {}
is_abstract: false
customs: []
